apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookservice-deployment
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: bookservice
        image: bookservice:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bookservice-service
spec:
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer