name: Build App

on:
    push:
        branches:
        - master

jobs:
    owasp:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: sburris/dependency-check-action@master
          with:
            Project-Name: book-service
        - name: Archive dependency check reports
          uses: actions/upload-artifact@v1
          with:
            name: reports
            path: reports
        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2        
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: isenitii2021/book-service
            tags: latest
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'docker.io/isenitii2021/book-service:latest'
            format: 'template'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
        - name: Upload Trivy scan results to GitHub Security tab            
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: 'trivy-results.sarif'
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
           # Disabling shallow clone is recommended for improving relevancy of reporting
           fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BOOK_SERVICE}}
